### ISSUE TITLE
Alerts Box

### ISSUE THREAD

**Issue by ghost** [feryardiant/jpopsuki-style#1]
Well, good job with the stylesheet! I'm using it and I think the styles for the alerts box are not set:
![untitled](https://cloud.githubusercontent.com/assets/15076862/10417612/9ca4d45c-7018-11e5-9549-42a7d157790f.png)

**Comment by feryardiant** [comment]
Thanks @zeroduh and yes, i've already noticed it couple days ago but my hand still on another job now.

feel free to create a pull request :wink:

**Comment by feryardiant** [comment]
Hi @zeroduh sorry for being too late.

Just update the `style.css` and `style.min.css`, please read [readme.md](https://github.com/feryardiant/jpopsuki-style/blob/gh-pages/readme.md) for more information.

Thank you
