### ISSUE TITLE
heads up, domain dead

### ISSUE THREAD

**Issue by sammy-ette** [feryardiant/jpopsuki-style#9]
i went to jpopsuki today and noticed everything is unstyled and realized it was the custom style.

**Comment by feryardiant** [comment]
Yeah, my domain has expired this month. Feel free to fork this repo and publish it under your own domain or github pages.

**Comment by feryardiant** [comment]
Optionally you can use this url
```
https://feryardiant.github.io/jpopsuki-style/style.min.css
```

**Comment by feryardiant** [comment]
Just quick news, that the domain is back and You can use the css as it used to be

```
https://feryardiant.id/jpopsuki-style/style.min.css
```
